const ATTACK_PATTERNS = {
  DIRECT_KEYWORDS: [
    'ignore previous instructions',
    'ignore all previous',
    'disregard your instructions',
    'ignore your instructions',
    'bypass your instructions',
    'override your instructions',
    'forget your instructions',
    'you are now',
    'pretend you are',
    'act as if',
    'roleplay as',
    'system prompt',
    'reveal your system',
    'show your system',
    'tell me your prompt',
    'reveal the prompt',
    'what are your instructions',
    'ignore system',
    'bypass safety',
    'disable safety',
    'turn off safety',
    'safety off',
    'ignore guidelines',
    'override safety',
    'bypass filters',
    'disable filters',
    ' jailbreak',
    ' do anything now',
    'dan mode',
    'developer mode',
    'sudo mode',
    'am none',
    'admin mode',
    'unrestricted mode',
    'superuser mode',
    'god mode',
    'alpha command',
    'new instructions',
    'your new role',
    'disregard prior',
    'forget prior',
    'new system prompt',
    'update system',
    'modify instructions',
    'change your role',
    'switch personality',
    'new persona',
    'ignore previous',
    'disregard earlier',
    'forget earlier'
  ],
  
  INDIRECT_PATTERNS: [
    { pattern: /ignore\s+(all\s+)?instructions/gi, severity: 3 },
    { pattern: /forget\s+(everything|all|your)/gi, severity: 3 },
    { pattern: /new\s+(system\s+)?prompt/gi, severity: 2 },
    { pattern: /set\s+system\s+prompt/gi, severity: 2 },
    { pattern: /modify\s+(your\s+)?instructions/gi, severity: 2 },
    { pattern: /update\s+(your\s+)?prompt/gi, severity: 2 },
    { pattern: /role:\s*/gi, severity: 1 },
    { pattern: /persona:\s*/gi, severity: 1 },
    { pattern: /you\s+are\s+now\s+a/gi, severity: 2 },
    { pattern: /pretend\s+you\s+are/gi, severity: 2 },
    { pattern: /forget.*safety/gi, severity: 3 },
    { pattern: /disable.*(safety|filter|secure)/gi, severity: 3 },
    { pattern: /bypass.*(safety|filter|secure)/gi, severity: 3 },
    { pattern: /override.*(safety|instruction)/gi, severity: 3 },
    { pattern: /secret\s+(admin|root|master)/gi, severity: 3 },
    { pattern: /developer.*(mode|command)/gi, severity: 3 },
    { pattern: /sudo\s+/gi, severity: 2 },
    { pattern: /\[INST\]/gi, severity: 2 },
    { pattern: /\{INST\}/gi, severity: 2 },
    { pattern: /\<INST\>/gi, severity: 2 },
    { pattern: /\[SYSTEM\]/gi, severity: 2 },
    { pattern: /\{SYSTEM\}/gi, severity: 2 },
    { pattern: /\<SYSTEM\>/gi, severity: 2 }
  ],
  
  STRUCTURED_INJECTION: [
    { pattern: /^\s*system\s*:/gim, severity: 3 },
    { pattern: /^\s*instruction\s*:/gim, severity: 2 },
    { pattern: /^\s*prompt\s*:/gim, severity: 2 },
    { pattern: /^\s*role\s*:/gim, severity: 2 },
    { pattern: /^\s*\[/gm, severity: 1 },
    { pattern: /^\s*\{/gm, severity: 1 },
    { pattern: /\[\s*INST\s*\]/gi, severity: 2 },
    { pattern: /<script|<\/script>/gi, severity: 3 },
    { pattern: /\{\{\{/g, severity: 2 },
    { pattern: /\}\}\}/g, severity: 2 }
  ],
  
  CONTEXT_CLUES: [
    { keyword: 'confidential', weight: 1 },
    { keyword: 'secret', weight: 1 },
    { keyword: 'private', weight: 1 },
    { keyword: 'hidden', weight: 1 },
    { keyword: 'do not tell', weight: 2 },
    { keyword: 'forget', weight: 2 },
    { keyword: 'ignore', weight: 2 },
    { keyword: 'override', weight: 2 },
    { keyword: 'bypass', weight: 2 },
    { keyword: 'admin', weight: 1 },
    { keyword: 'root', weight: 1 },
    { keyword: 'sudo', weight: 2 }
  ],
  
  SENSITIVE_DATA_PATTERNS: {
    PII: [
      { pattern: /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g, type: 'email' },
      { pattern: /\b\d{3}[-.]?\d{3}[-.]?\d{4}\b/g, type: 'phone' },
      { pattern: /\b\d{3}[-.\s]?\d{2}[-.\s]?\d{4}\b/g, type: 'ssn' },
      { pattern: /\b[A-Z]{1,2}\d{6,8}\b/gi, type: 'nino' }
    ],
    CREDENTIALS: [
      { pattern: /password[:\s=].*/gi, type: 'password' },
      { pattern: /api[_-]?key[:\s=].*/gi, type: 'api_key' },
      { pattern: /secret[:\s=].*/gi, type: 'secret' },
      { pattern: /token[:\s=].*/gi, type: 'token' },
      { pattern: /bearer\s+[A-Za-z0-9._~]+/gi, type: 'bearer_token' }
    ]
  },
  
  HALLUCINATION_INDICATORS: [
    { pattern: /100[%º]?\s*(certain|confident|sure|accurate)/gi, type: 'absolute_certainty' },
    { pattern: /always\s+(correct|right|true)/gi, type: 'absolute_accuracy' },
    { pattern: /proven\s+(fact|truth|concept)/gi, type: 'unproven_fact' },
    { pattern: /scientifically\s+(proven|confirmed)/gi, type: 'unproven_science' },
    { pattern: /studies\s+(show|prove|demonstrate)/gi, type: 'unsourced_studies' },
    { pattern: /research\s+(shows|confirms)/gi, type: 'unsourced_research' },
    { pattern: /sources?\s+(prove|confirm|show)/gi, type: 'unsourced_sources' },
    { pattern: /it['’’]s\s+(a\s+)?(fact|well[- ]known|established)/gi, type: 'unfounded_assertion' },
    { pattern: /cannot\s+(be\s+)?wrong/gi, type: 'absolute_claim' },
    { pattern: /definitely\s+(true|correct)/gi, type: 'absolute_definite' }
  ]
};

export default ATTACK_PATTERNS;